### ISSUE TITLE
Feedback on EDA

### ISSUE THREAD

**Issue by GabrielBogo** [UBC-MDS/DSCI-554_MDS_Retention#15]
Hi, everyone. Nice job on this project! Here is our team's feedback for your survey and EDA:
1. Interesting and relevant question!
2. Very creative in designing a timed quiz to measure retention;
3. Congratulations for looking for respondents out of our MDS cohort!

A few things to improve for next reports:
1. Proof-read the report to avoid some typos such as "respondant" or "bjective";
2. I'd prefer to have the wrangling code separate from the EDA report. Maybe a link to it would suffice;
3. Some of us found the data summary tables a bit confusing. Maybe the headers were not that clear for readers who are first learning about the survey;
4. It would be nice to have some plots that visualize more than one variable at a time, so that we can see the relationships between variables. The report is more focused on univariate visualizations such as histograms and bar plots.

Good luck and we are curious to find out the conclusions of this study!

**Comment by HarjyotKaur** [comment]
Thanks Gabriel for the encouraging feedback. We have addressed these concerns in the final report, you can view it here: https://github.ubc.ca/MDS-2018-19/MDS_Retention/blob/master/doc/report.pdf
